---
- hosts: all
  
  become: yes
  become_method: sudo

  tasks:
  - name: generate locale de_CH.utf8
    command: locale-gen de_CH.utf8
  - name: install Java Runtime Environment version 8 and zip
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - openjdk-8-jre-headless
    - zip
  - name: create directory /opt/gradle
    file:
      path: /opt/gradle
      state: directory
      mode: 0755
  - name: download and unzip Gradle
    unarchive:
      src: https://services.gradle.org/distributions/gradle-3.5.1-bin.zip
      dest: /opt/gradle
      remote_src: yes
  - name: Add path to Gradle binary to the PATH variable
    lineinfile:
      path: /etc/environment
      regexp: '^PATH='
      line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/gradle/gradle-3.5.1/bin"'

  - name: Start gradle to have .gradle directory
    shell: /opt/gradle/gradle-3.5.1/bin/gradle
    become: vagrant

  - name: Copy init.gradle in Ordner ~/.gradle
    copy: src='/vagrant/init.gradle' 
          dest='/home/vagrant/.gradle/init.gradle'
          owner=vagrant
          group=vagrant
          mode=0755
