["meta"]
identifier = "ch.so.arp.bauzonengrenzen"
title = "Bauzonengrenzen"
description = """
Bauzonengrenzen abgeleitet aus den digitalen Daten der Nutzungsplanung. Es werden die kantonalen Zonentypen 110 - 190 und 430 - 439 berücksichtig und zwischen Reserverzone und Bauzone unterschieden.
"""
keywords = "Bauzonen,Bauzone,Nutzungsplanung"
synonyms = "Bauzonen,Bauzone"
model = "SO_ARP_Bauzonengrenzen_20210120"
owner = "ch.so.arp"
servicer = "ch.so.agi"
licence = "https://files.geo.so.ch/nutzungsbedingungen.html"
formats = ["XTF", "GPKG", "SHP", "DXF"]
